apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Composition

modulesFrom:
- path: base/composition.yaml

moduleOverrides:
- apiVersion: team.example.com/v1alpha1
  kind: HTTPLoadBalancer
  metadata:
    name: lb
  spec:
    loadBalancer:
      domain: foo.app.example.com

modules:
- apiVersion: kustomize.config.k8s.io/v1alpha1
  kind: Kustomize
  metadata:
    name: productionizer
  spec:
    commonLabels:
      env: production
    namespace: nginx-example-prod
