apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - plugins-base

patchesStrategicMerge:
  - |-
    apiVersion: team.example.com/v1alpha1
    kind: HTTPLoadBalancer
    metadata:
      name: lb
    spec:
      loadBalancer:
        domain: foo.app.example.com

