apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prod-integration-base

# This layer is needed because the plugins are transformers, and the transformers field is executed after the built-in like the label transformer. So most of the resources wouldn't be labelled if we included this in prod-integration-base instead.
commonLabels:
  env: production
  foo: bar # Ideally this label would be at a lower layer, but that won't work.

namespace: nginx-example-prod
